name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.AZURE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -i ~/ssh_key \
            -o StrictHostKeyChecking=no \
            azureuser@20.197.11.199 << 'EOF'

            cd bms || exit

            git pull origin main

            export PATH=/home/azureuser/.nvm/versions/node/v24.8.0/bin:$PATH

            npm install -g pnpm

            pnpm install

            pnpm run build

            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server

          EOF
